# Generated by Django 6.0.4 on 2026-05-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
