# Generated by Django 6.0.4 on 2026-05-05 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('workday', 'Work Day'), ('regular_holiday', 'Regular Holiday'), ('special_holiday', 'Special Holiday'), ('rest', 'Rest Day')], default='workday', max_length=30)),
                ('is_paid', models.BooleanField(default=True)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
