# Generated by Django 6.0.4 on 2026-05-05 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='operator',
            field=models.CharField(choices=[('+', 'Add (+)'), ('-', 'Subtract (−)'), ('*', 'Multiply (×)'), ('/', 'Divide (÷)')], default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='pct_base',
            field=models.CharField(blank=True, default='basic_pay', max_length=50),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollcomponent',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Variable'), ('formula', 'Custom Formula')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollcomponent',
            name='default_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollcomponent',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
