# Generated by Django 6.0.4 on 2026-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salarygrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='type',
            field=models.CharField(choices=[('leave', 'Leave'), ('overtime', 'Overtime'), ('deduction', 'Deduction'), ('allowance', 'Allowance')], max_length=20),
        ),
    ]
